version: '3'
services: 
  app: 
    build: ./
    volumes: 
      - ./:/app
    working_dir: /app
    ports: 
      - 3000:3000
    command: yarn start
    links: 
      - "mysql-server:ms"
      - "redis-server:rd"
    depends_on: 
      - mysql-server
      - redis-server

  mysql-server:
    image: mysql:5.5
    ports: 
      - 3306:3306
    expose: 
      - 3306
    command: [
      '--default-authentication-plugin=mysql_native_password',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
    environment: 
      - MYSQL_ROOT_PASSWORD=123456

  redis-server:
    image: redis
    ports: 
      - 6379:6379
    expose: 
      - 6379
